# Generated by Django 3.0.4 on 2021-06-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_auto_20210608_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolyear_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdg_goal', models.CharField(max_length=150)),
                ('halfyear', models.IntegerField(verbose_name='Полугодие')),
                ('schoolyear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.SchoolYear')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FocusPlan1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId_observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer', to='focus.UserProfileInfo')),
                ('UserId_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='focus.UserProfileInfo')),
            ],
        ),
    ]
