# Generated by Django 3.0.4 on 2021-06-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_focusplan1_pdg_schoolyear_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField(default=9)),
            ],
        ),
        migrations.RenameField(
            model_name='focusplan1',
            old_name='UserId_observer',
            new_name='user_observer',
        ),
        migrations.RenameField(
            model_name='focusplan1',
            old_name='UserId_teacher',
            new_name='user_teacher',
        ),
        migrations.RenameField(
            model_name='pdg',
            old_name='schoolyear_id',
            new_name='schoolyear',
        ),
        migrations.RenameField(
            model_name='pdg',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='pdg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='focus.Pdg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='schoolyear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='focus.SchoolYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='focus.Subject'),
            preserve_default=False,
        ),
    ]
