# Generated by Django 3.0.4 on 2021-06-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_auto_20210622_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusplan1',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='focus.Classes'),
            preserve_default=False,
        ),
    ]
