# Generated by Django 3.0.4 on 2021-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_focusplan1_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item1',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item2',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item3',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item4',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item5',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item6',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item7',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_lessontopic',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
