# Generated by Django 3.0.4 on 2021-06-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_auto_20210622_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusplan1',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_date',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item1',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item2',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item3',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item4',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item5',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item6',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_item7',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='fp1_lessontopic',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='pdg',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='schoolyear',
        ),
        migrations.RemoveField(
            model_name='focusplan1',
            name='subject',
        ),
    ]
