# Generated by Django 3.0.4 on 2021-06-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0007_auto_20210624_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusplan1',
            name='classes',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Classes'),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='pdg',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Pdg'),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='schoolyear',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.SchoolYear'),
        ),
        migrations.AddField(
            model_name='focusplan1',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Subject'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(max_length=15),
        ),
    ]
