# Generated by Django 3.0.4 on 2021-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0008_auto_20210624_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_lessontopic',
            field=models.CharField(default='чтение', max_length=150),
        ),
    ]
