# Generated by Django 3.0.4 on 2021-07-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0009_focusplan1_fp1_lessontopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item1',
            field=models.IntegerField(choices=[(1, 'Самостоятельно разработанного урока'), (2, 'Совместно разработанного с коллегами урока в рамках исследования урока'), (3, 'Урока в рамках исследования практики'), (4, 'Урока по авторской программе'), (5, 'Урока по авторской методике')], default=1),
        ),
        migrations.AlterField(
            model_name='focusplan1',
            name='fp1_lessontopic',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
