# Generated by Django 3.0.4 on 2021-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0010_auto_20210704_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusplan1',
            name='fp1_item2',
            field=models.BooleanField(default=True),
        ),
    ]
