# Generated by Django 3.0.4 on 2021-08-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0012_auto_20210704_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusplan1',
            name='user_observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_plan', to='focus.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='focusplan1',
            name='user_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plan', to='focus.UserProfileInfo'),
        ),
        migrations.CreateModel(
            name='FocusTeach1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft1_date', models.DateField(auto_now=True)),
                ('ft1_lessontopic', models.CharField(default=' ', max_length=150)),
                ('ft1_item1', models.IntegerField(choices=[(1, 'Самостоятельно разработанного урока'), (2, 'Совместно разработанного с коллегами урока в рамках исследования урока'), (3, 'Урока в рамках исследования практики'), (4, 'Урока по авторской программе'), (5, 'Урока по авторской методике')], default=1)),
                ('ft1_item2', models.BooleanField(default=True)),
                ('ft1_item3', models.BooleanField(default=True)),
                ('ft1_item4', models.IntegerField(choices=[(1, 'Взаимосвязь темы с другими темами и разделами учебной программы'), (2, 'Преемственность темы урока и непрерывности ее изучения'), (3, 'Межпредметные связи учебной программы'), (4, 'Идеи авторской программы'), (5, 'Идеи авторской методики')], default=1)),
                ('ft1_item5', models.BooleanField(default=True)),
                ('ft1_item6', models.IntegerField(choices=[(1, 'Удовлетворение потребностей учащихся'), (2, 'Развитие способностей учащихся'), (3, 'Развитие исследовательских навыков'), (4, 'Развитие проектно- исследовательских навыков'), (5, 'Развитие навыков проектной деятельности')], default=1)),
                ('ft1_review', models.CharField(default=' ', max_length=150)),
                ('ft1_review_pdg', models.CharField(default=' ', max_length=150)),
                ('ft1_additional', models.CharField(default=' ', max_length=150)),
                ('classes', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Classes')),
                ('pdg', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Pdg')),
                ('schoolyear', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.SchoolYear')),
                ('subject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Subject')),
                ('user_observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_teach', to='focus.UserProfileInfo')),
                ('user_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_teach', to='focus.UserProfileInfo')),
            ],
        ),
    ]
