# Generated by Django 3.0.4 on 2021-08-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0013_auto_20210803_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusEvaluation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft1_date', models.DateField(auto_now=True)),
                ('fe1_lessontopic', models.CharField(default=' ', max_length=150)),
                ('fe1_item1', models.BooleanField(default=True)),
                ('fe1_item2', models.BooleanField(default=True)),
                ('fe1_item3', models.BooleanField(default=True)),
                ('fe1_item4', models.BooleanField(default=True)),
                ('fe1_item5', models.BooleanField(default=True)),
                ('fe1_review', models.CharField(default=' ', max_length=150)),
                ('fe1_review_pdg', models.CharField(default=' ', max_length=150)),
                ('fe1_additional', models.CharField(default=' ', max_length=150)),
                ('classes', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Classes')),
                ('pdg', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Pdg')),
                ('schoolyear', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.SchoolYear')),
                ('subject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Subject')),
                ('user_observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_evaluation', to='focus.UserProfileInfo')),
                ('user_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_evaluation', to='focus.UserProfileInfo')),
            ],
        ),
    ]
