# Generated by Django 3.0.4 on 2021-08-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0014_focusevaluation1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusComplex1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft1_date', models.DateField(auto_now=True)),
                ('fc1_lessontopic', models.CharField(default=' ', max_length=150)),
                ('fc1_item1', models.IntegerField(choices=[(1, 'Самостоятельно разработанного урока'), (2, 'Совместно разработанного с коллегами урока в рамках исследования урока'), (3, 'Урока в рамках исследования практики'), (4, 'Урока по авторской программе'), (5, 'Урока по авторской методике')], default=1)),
                ('fc1_item2', models.BooleanField(default=True)),
                ('fc1_item3', models.BooleanField(default=True)),
                ('fc1_item4', models.BooleanField(default=True)),
                ('fc1_item5', models.IntegerField(choices=[(1, 'Взаимосвязь темы с другими темами и разделами учебной программы'), (2, 'Преемственность темы урока и непрерывности ее изучения'), (3, 'Межпредметные связи учебной программы'), (4, 'Идеи авторской программы'), (5, 'Идеи авторской методики')], default=1)),
                ('fc1_item6', models.BooleanField(default=True)),
                ('fc1_item7', models.IntegerField(choices=[(1, 'Удовлетворение потребностей учащихся'), (2, 'Развитие способностей учащихся'), (3, 'Развитие исследовательских навыков'), (4, 'Развитие проектно- исследовательских навыков'), (5, 'Развитие навыков проектной деятельности')], default=1)),
                ('fc1_item8', models.BooleanField(default=True)),
                ('fc1_item9', models.BooleanField(default=True)),
                ('fc1_item10', models.BooleanField(default=True)),
                ('fc1_item11', models.BooleanField(default=True)),
                ('fc1_item12', models.BooleanField(default=True)),
                ('fc1_review', models.CharField(default=' ', max_length=150)),
                ('fc1_review_pdg', models.CharField(default=' ', max_length=150)),
                ('classes', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Classes')),
                ('pdg', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Pdg')),
                ('schoolyear', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.SchoolYear')),
                ('subject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='focus.Subject')),
                ('user_observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_complex', to='focus.UserProfileInfo')),
                ('user_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_complex', to='focus.UserProfileInfo')),
            ],
        ),
    ]
