# Generated by Django 3.0.4 on 2021-08-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0015_focuscomplex1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focuscomplex1',
            old_name='ft1_date',
            new_name='fc1_date',
        ),
        migrations.RenameField(
            model_name='focusevaluation1',
            old_name='ft1_date',
            new_name='fe1_date',
        ),
    ]
