# Generated by Django 3.0.4 on 2021-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0016_auto_20210803_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_level',
            field=models.IntegerField(verbose_name='Статус'),
        ),
    ]
