# Generated by Django 3.0.4 on 2021-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0018_auto_20210905_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusplan1',
            name='fp1_item2_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='focusplan1',
            name='fp1_item3_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='focusplan1',
            name='fp1_item5_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='focusplan1',
            name='fp1_item6_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='focusplan1',
            name='fp1_item7_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
    ]
