# Generated by Django 3.0.4 on 2021-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0019_auto_20210905_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusteach1',
            name='ft1_item2_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusteach1',
            name='ft1_item3_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusteach1',
            name='ft1_item5_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
    ]
