# Generated by Django 3.0.4 on 2021-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0020_auto_20210905_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusevaluation1',
            name='fe1_item1_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusevaluation1',
            name='fe1_item2_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusevaluation1',
            name='fe1_item3_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusevaluation1',
            name='fe1_item4_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='focusevaluation1',
            name='fe1_item5_comm',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
    ]
